- name: disable nginx
  ansible.builtin.shell: dnf module disable nginx -y

- name: env name
  ansible.builtin.debug:
    msg: "{{ env }}"

- name: enable nginx
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Copy relevent nginx files
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf.j2

- name: Remove old app directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create App content directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /usr/share/nginx/html
    remote_src: yes


- name: Start Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes

- name: Check NGINX status
  ansible.builtin.systemd:
    name: nginx
    state: started
  register: nginx_status

- name: Show NGINX status
  ansible.builtin.debug:
    var: nginx_status

- name: Check if NGINX is listening on port 80
  ansible.builtin.shell: "netstat -tuln | grep :80"
  register: netstat_check
  failed_when: netstat_check.rc != 0

- name: Show netstat check result
  ansible.builtin.debug:
    var: netstat_check







