- name: disable nodejs
  ansible.builtin.shell: dnf module disable nodejs -y

- name: enable nodejs 20
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: Install Nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present


- name: Include systemd file
  ansible.builtin.include_tasks:
    file: artifact_download.yml

- name: Install NodeJs Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app



- name: copy SystemD service file
  ansible.builtin.template:
    src: {{ component_name }}.service.j2
    dest: /etc/systemd/system/{{ component_name }}.service

- name: start Service
  ansible.builtin.systemd_service:
    name: {{ component_name }}
    state: restarted
    enabled: yes
    daemon_reload: yes

#- name: Include systemd file
#  ansible.builtin.include_tasks:
#    file: systemd_setup.yml