#dnf install python3 gcc python3-devel -y
#app_pre_req
#artificat_download
#cd /app
#pip3 install -r requirements.txt
#
#systemmd_setup

- name: Install Python Packages
  ansible.builtin.dnf:
    name:
      - python3
      - gcc
      - python3-devel
    state: present

- name: Show current working directory
  ansible.builtin.command: pwd
  register: pwd_output

- name: Display pwd result
  ansible.builtin.debug:
    var: pwd_output.stdout

- name: Create /app directory
  ansible.builtin.file:
    path: /app
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'


- name: Install NodeJs Dependencies
  ansible.builtin.command: pip3 install -r requirements.txt
  args:
    chdir: /app

- name: Include systemd file
  ansible.builtin.include_tasks:
    file: artifact_download.yml


- name: Include systemd file
  ansible.builtin.include_tasks:
    file: systemd_setup.yml






















