#dnf install python3 gcc python3-devel -y
#app_pre_req
#artificat_download
#cd /app
#pip3 install -r requirements.txt
#
#systemmd_setup

- name: Install Python Packages
  ansible.builtin.dnf:
    name:
      - python3
      - gcc
      - python3-devel
    state: present

- name: Install NodeJs Dependencies
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
    chdir: /app

- name: Include systemd file
  ansible.builtin.include_tasks:
    file: artifact_download.yml


- name: Include systemd file
  ansible.builtin.include_tasks:
    file: systemd_setup.yml






















